# This is a config for E2B sandbox template.
# You can use template ID (v96cr2p1wrrhw43tn82w) or template name (linqvibe-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("linqvibe-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("linqvibe-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('linqvibe-nextjs-test-2')

team_id = "c835c698-e525-42cc-9424-8fbad5e9c4e2"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "linqvibe-nextjs-test-2"
template_id = "v96cr2p1wrrhw43tn82w"
